### ISSUE TITLE
并发线程提交数据Connection reset by peer

### ISSUE THREAD

**Issue by lvchangbin1207** [WeBankFinTech/eggroll#437]
Exception in thread roll_pair-send_command-90f32f70-dba0-11ea-88c4-fa163e1070a0-py-job-93d9f2a0-dba0-11ea-8514-fa163e1070a0_putAll:
Traceback (most recent call last):
  File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 71, in sync_send
    response = _command_stub.call(request.to_proto())
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connection reset by peer"
        debug_error_string = "{"created":"@1597129331.341114809","description":"Error received from peer ipv4:xx.xx.xx.xx:32882","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Connection reset by peer","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/common/miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/data/projects/fate/common/miniconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/roll_pair.py", line 568, in send_command
    serdes_type=SerdesTypes.PROTOBUF)
  File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 54, in simple_sync_send
    results = self.sync_send(inputs=[input], output_types=[output_type], endpoint=endpoint, command_uri=command_uri, serdes_type=serdes_type)
  File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 84, in sync_send
    raise CommandCallError(command_uri, endpoint, e)
eggroll.core.client.CommandCallError: ('Failed to call command: CommandURI(_uri=v1/roll-pair/runJob) to endpoint: xx.xx.xx.xx:32882, caused by: ', <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connection reset by peer"
        debug_error_string = "{"created":"@1597129331.341114809","description":"Error received from peer ipv4:xx.xxx.xx.xx:32882","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Connection reset by peer","grpc_status":14}"
>)

**Comment by drougon** [comment]
unsupported now

**Comment by maxwong** [comment]
Closing this issue as there is no update for more than 1 month.

Please reopen this issue when necessary.
